### ISSUE TITLE
0.5.0版本对Coolapk不起作用

### ISSUE THREAD

**Issue by Beattheend** [ejiaogl/FuckCoolapk#30]
0.5.0版本对Coolapk不起作用，Coolapk设置里显示了模块但所有作用于Coolapk功能不生效，点击模块里的“Github”会闪退。
酷安版本：11.1.0 2103251
模块版本：0.5.0 20120327
LSP框架版本：V1.3.4 5516
日志：

2021-03-28 00:32:51.051 I/com.coolapk.market(28206-28206): FUCKCOOLAPK : de.robv.android.xposed.XposedHelpers$InvocationTargetError: java.lang.NullPointerException: Attempt to invoke virtual method 'com.coolapk.market.util.PreferencesUtils$EditorHelper com.coolapk.market.util.PreferencesUtils.edit()' on a null object reference
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:20)
	at com.bytedance.sdk.openadsdk.a.d.胡松华丢你老母个嗨(:42)
	at com.bytedance.sdk.openadsdk.a.d$胡松华丢你老母个嗨.afterHookedMethod(:4)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.attachBaseContext(Unknown Source:11)
	at android.app.Application.attach(Application.java:353)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1158)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1240)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6963)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.handleBindApplication(Unknown Source:11)
	at android.app.ActivityThread.access$1500(ActivityThread.java:258)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1974)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8061)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.coolapk.market.util.PreferencesUtils$EditorHelper com.coolapk.market.util.PreferencesUtils.edit()' on a null object reference
	at com.coolapk.market.manager.DataManager.getPreferencesEditor(DataManager.java:2084)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:8)
	... 19 more

2021-03-28 00:32:53.053 I/com.coolapk.market:xg_vip_service(7786-7786): FUCKCOOLAPK : de.robv.android.xposed.XposedHelpers$InvocationTargetError: java.lang.NullPointerException: Attempt to invoke virtual method 'com.coolapk.market.util.PreferencesUtils$EditorHelper com.coolapk.market.util.PreferencesUtils.edit()' on a null object reference
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:20)
	at com.bytedance.sdk.openadsdk.a.d.胡松华丢你老母个嗨(:42)
	at com.bytedance.sdk.openadsdk.a.d$胡松华丢你老母个嗨.afterHookedMethod(:4)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.attachBaseContext(Unknown Source:11)
	at android.app.Application.attach(Application.java:353)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1158)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1240)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6963)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.handleBindApplication(Unknown Source:11)
	at android.app.ActivityThread.access$1500(ActivityThread.java:258)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1974)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8061)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.coolapk.market.util.PreferencesUtils$EditorHelper com.coolapk.market.util.PreferencesUtils.edit()' on a null object reference
	at com.coolapk.market.manager.DataManager.getPreferencesEditor(DataManager.java:2084)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:8)
	... 19 more

我对日志里的中文表示疑惑，0.4.3版本没有该问题。

**Comment by xushet** [comment]
+1不生效

**Comment by Beattheend** [comment]
> ~+1不生效~
> 
> 关闭模块设置里的去广告原生模式就好了

真的诶，哈哈，我一股脑全开了，谢谢。
