### ISSUE TITLE
[BUG] coolapk_with_fuckcoolapk_0.5.8.apk 闪退

### ISSUE THREAD

**Issue by dazzleme** [ejiaogl/FuckCoolapk#91]
**情况描述？安装coolapk_with_fuckcoolapk_0.5.8.apk后打不开

**对酷安生效的 Xposed 模块列表：未安装Xposed

**版本信息：0.5.8

Android:12

LSPosed:未安装LSPosed

Coolapk: 11.1.5.1

Devices:Redmi k40 

**相关日志：**
[11-04 13:10:41.468 1669:2064 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.coolapk.market flg=0x4000010 (has extras) } to com.android.vending/com.google.android.finsky.packagemanager.impl.PackageMonitorReceiverImpl$RegisteredReceiver

[11-04 13:10:41.469 1669:1723 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.coolapk.market flg=0x4000010 (has extras) } to com.google.android.gms/.games.chimera.GamesSystemBroadcastReceiverProxy

[11-04 13:10:41.469 1669:1723 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.coolapk.market flg=0x4000010 (has extras) } to com.google.android.gms/.gass.chimera.PackageChangeBroadcastReceiver

[11-04 13:10:41.469 1669:1723 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.coolapk.market flg=0x4000010 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver

[11-04 13:10:41.469 1669:1723 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.coolapk.market flg=0x4000010 (has extras) } to com.google.android.googlequicksearchbox/com.google.android.apps.gsa.googlequicksearchbox.GelStubAppWatcher

[11-04 13:10:41.469 1669:1723 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.coolapk.market flg=0x4000010 (has extras) } to com.google.android.ims/.receivers.RcsAutoStartReceiver

[11-04 13:10:41.469 1669:1723 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.coolapk.market flg=0x4000010 (has extras) } to com.verizon.mips.services/com.vzw.hss.myverizon.rdd.analytics.receiver.RDDAnalyticsPackageActionReceiver

[11-04 13:10:41.469 1669:1723 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.coolapk.market flg=0x4000010 (has extras) } to com.verizon.mips.services/com.verizon.vzwavs.receiver.AVSBaseReceiver

[11-04 13:10:41.469 1669:1723 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.coolapk.market flg=0x4000010 (has extras) } to com.verizon.mips.services/com.verizon.vzwavs.receiver.AVSImplicitBroadcastReceiver

[11-04 13:10:41.469 1669:1723 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.coolapk.market flg=0x4000010 (has extras) } to com.autonavi.minimap/.app.update.InstallListener

[11-04 13:10:41.470 1669:1745 E/VerityUtils]
Failed to measure fs-verity, errno 1: /data/app/~~WQA-cNIxLKoKk_5vHMOPQw==/com.coolapk.market-fGhBSqFdmHUxdzw7BCS4bw==/base.apk

[11-04 13:10:41.475 3005:3028 W/GCM]
Unexpected forwarded intent: Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.coolapk.market flg=0x4000010 pkg=com.google.android.gms cmp=com.google.android.gms/.chimera.PersistentIntentOperationService (has extras) }

[11-04 13:10:41.477 3005:3254 W/GCM]
Unexpected forwarded intent: Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.coolapk.market flg=0x4000010 pkg=com.google.android.gms cmp=com.google.android.gms/.chimera.PersistentIntentOperationService (has extras) }

[11-04 13:10:41.479 2509:2509 D/ImsResolver]
maybeAddedImsService, packageName: com.coolapk.market

[11-04 13:10:41.484 1669:1710 D/CompanionDeviceManagerService]
onPackageModified(packageName = com.coolapk.market)

[11-04 13:10:41.485 1669:1723 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.coolapk.market flg=0x4000010 (has extras) } to com.mihoyo.hyperion/cn.jpush.android.service.PushReceiver

[11-04 13:10:41.485 3005:3028 I/Fitness]
OnPackageChangedOperation got intent: Intent { act=android.intent.action.PACKAGE_CHANGED dat=package:com.coolapk.market flg=0x5000010 pkg=com.google.android.gms cmp=com.google.android.gms/.chimera.PersistentIntentOperationService (has extras) } [CONTEXT service_id=17 ]

[11-04 13:10:41.575 24158:24158 I/Finsky]
[2] tho.n(8): Invalidating cached PackageState for com.coolapk.market

[11-04 13:10:41.629 24158:24236 I/Finsky]
[44] fro.a(5): AIM: AppInfoManager-Perf > OnDeviceAppInfo > cacheHitCount=0, cacheMissCount=1. Missed  in cache (limit 10) : [com.coolapk.market]

[11-04 13:10:41.650 3005:3258 I/Fitness]
OnPackageChangedOperation got intent: Intent { act=android.intent.action.PACKAGE_CHANGED dat=package:com.coolapk.market flg=0x5000010 pkg=com.google.android.gms cmp=com.google.android.gms/.chimera.PersistentIntentOperationService (has extras) } [CONTEXT service_id=17 ]

[11-04 13:10:41.708 16179:16179 I/AiAiEcho]
EchoSearch: AppFetcherImpl is initialized with [55] apps [time=15, reason=com.coolapk.market is added]

[11-04 13:10:41.953 1669:16192 V/AppSearchResult]
Converting throwable to failed result: android.app.appsearch.exceptions.AppSearchException: Document (android$com.coolapk.market/com.coolapk.market, QR_SCAN) not found.

[11-04 13:10:41.956 1669:16192 V/AppSearchResult]
Converting throwable to failed result: android.app.appsearch.exceptions.AppSearchException: Document (android$com.coolapk.market/com.coolapk.market, QR_SCAN) not found.

[11-04 13:10:41.989 1669:16192 V/AppSearchResult]
Converting throwable to failed result: android.app.appsearch.exceptions.AppSearchException: Document (android$com.coolapk.market/com.coolapk.market, SEARCH) not found.

[11-04 13:10:41.991 1669:16192 V/AppSearchResult]
Converting throwable to failed result: android.app.appsearch.exceptions.AppSearchException: Document (android$com.coolapk.market/com.coolapk.market, SEARCH) not found.

[11-04 13:10:42.018 1669:16192 V/AppSearchResult]
Converting throwable to failed result: android.app.appsearch.exceptions.AppSearchException: Document (android$com.coolapk.market/com.coolapk.market, NEW_FEED) not found.

[11-04 13:10:42.020 1669:16192 V/AppSearchResult]
Converting throwable to failed result: android.app.appsearch.exceptions.AppSearchException: Document (android$com.coolapk.market/com.coolapk.market, NEW_FEED) not found.

[11-04 13:10:42.048 1669:16192 V/AppSearchResult]
Converting throwable to failed result: android.app.appsearch.exceptions.AppSearchException: Document (android$com.coolapk.market/com.coolapk.market, COOL_PIC) not found.

[11-04 13:10:42.049 1669:16192 V/AppSearchResult]
Converting throwable to failed result: android.app.appsearch.exceptions.AppSearchException: Document (android$com.coolapk.market/com.coolapk.market, COOL_PIC) not found.

[11-04 13:10:42.085 1669:16192 V/AppSearchResult]
Converting throwable to failed result: android.app.appsearch.exceptions.AppSearchException: Document (android$com.coolapk.market/com.coolapk.market, APP_MANAGER) not found.

[11-04 13:10:42.086 1669:16192 V/AppSearchResult]
Converting throwable to failed result: android.app.appsearch.exceptions.AppSearchException: Document (android$com.coolapk.market/com.coolapk.market, APP_MANAGER) not found.

[11-04 13:10:49.367 2647:2717 D/AddWorkspaceItemsTask]
Adding item info to workspace: WorkspaceItemInfo(id=55 type=APP container=# com.android.launcher3.logger.LauncherAtom$ContainerInfo@2998857
workspace {
  grid_x: 3
  grid_y: 4
  page_index: 2
} targetComponent=ComponentInfo{com.coolapk.market/com.coolapk.market.view.main.MainActivity} screen=2 cell(3,4) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} title=CoolApk)

[11-04 13:10:51.179 1669:11049 I/ActivityTaskManager]
START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.coolapk.market/.view.main.MainActivity bnds=[812,1466][1022,1738]} from uid 10163

[11-04 13:10:51.221 1669:1724 I/ActivityManager]
Start proc 3568:com.coolapk.market/u0a230 for pre-top-activity {com.coolapk.market/com.coolapk.market.view.main.MainActivity}

[11-04 13:10:51.269 3568:3568 V/GraphicsEnvironment]
ANGLE Developer option for 'com.coolapk.market' set to: 'default'

[11-04 13:10:51.284 3568:3568 D/XpatchProxyApplication]
 original_application_name = com.coolapk.market.CoolMarketApplication

[11-04 13:10:51.304 3568:3568 E/DexLoadReporter]
Could not create the profile directory: /data/user/0/com.coolapk.market/cache/sandxposed/oat/SandHookerNew_23ukegmeinpecs216grvq3ms01.jar.cur.prof

[11-04 13:10:51.329 3568:3568 D/XposedModuleEntry]
Current truely loaded module path ----> /data/app/~~WQA-cNIxLKoKk_5vHMOPQw==/com.coolapk.market-fGhBSqFdmHUxdzw7BCS4bw==/lib/arm64/libxpatch_xp_module_0.so

[11-04 13:10:51.356 3568:3568 F/libc]
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7300007c64 in tid 3568 (.coolapk.market), pid 3568 (.coolapk.market)

[11-04 13:10:51.586 3589:3589 F/DEBUG]
Cmdline: com.coolapk.market

[11-04 13:10:51.586 3589:3589 F/DEBUG]
pid: 3568, tid: 3568, name: .coolapk.market  >>> com.coolapk.market <<<

[11-04 13:10:51.586 3589:3589 F/DEBUG]
      #07 pc 000000000248fa56  /data/app/~~WQA-cNIxLKoKk_5vHMOPQw==/com.coolapk.market-fGhBSqFdmHUxdzw7BCS4bw==/oat/arm64/base.vdex

[11-04 13:10:51.586 3589:3589 F/DEBUG]
      #09 pc 000000000248faee  /data/app/~~WQA-cNIxLKoKk_5vHMOPQw==/com.coolapk.market-fGhBSqFdmHUxdzw7BCS4bw==/oat/arm64/base.vdex

[11-04 13:10:51.586 3589:3589 F/DEBUG]
      #11 pc 0000000002494b0a  /data/app/~~WQA-cNIxLKoKk_5vHMOPQw==/com.coolapk.market-fGhBSqFdmHUxdzw7BCS4bw==/oat/arm64/base.vdex

[11-04 13:10:51.586 3589:3589 F/DEBUG]
      #13 pc 0000000002499d0c  /data/app/~~WQA-cNIxLKoKk_5vHMOPQw==/com.coolapk.market-fGhBSqFdmHUxdzw7BCS4bw==/oat/arm64/base.vdex

[11-04 13:10:51.606 1669:3592 W/ActivityTaskManager]
  Force finishing activity com.coolapk.market/.view.main.MainActivity

[11-04 13:10:51.608 1669:3592 W/ActivityTaskManager]
Failed to send top-resumed=false to ActivityRecord{50ca530 u0 com.coolapk.market/.view.main.MainActivity t479 f}}
android.os.DeadObjectException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:571)
	at android.app.IApplicationThread$Stub$Proxy.scheduleTransaction(IApplicationThread.java:2732)
	at android.app.servertransaction.ClientTransaction.schedule(ClientTransaction.java:136)
	at com.android.server.wm.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:47)
	at com.android.server.wm.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:85)
	at com.android.server.wm.ActivityRecord.scheduleTopResumedActivityChanged(ActivityRecord.java:1230)
	at com.android.server.wm.ActivityTaskSupervisor.updateTopResumedActivityIfNeeded(ActivityTaskSupervisor.java:2106)
	at com.android.server.wm.TaskDisplayArea.positionChildTaskAt(TaskDisplayArea.java:470)
	at com.android.server.wm.TaskDisplayArea.positionChildAt(TaskDisplayArea.java:414)
	at com.android.server.wm.WindowContainer.positionChildAt(WindowContainer.java:742)
	at com.android.server.wm.Task.positionChildAt(Task.java:3184)
	at com.android.server.wm.Task.moveToFront(Task.java:5530)
	at com.android.server.wm.ActivityRecord.moveFocusableActivityToTop(ActivityRecord.java:2799)
	at com.android.server.wm.TaskDisplayArea.moveHomeActivityToTop(TaskDisplayArea.java:1854)
	at com.android.server.wm.Task.adjustFocusToNextFocusableTask(Task.java:3093)
	at com.android.server.wm.ActivityRecord.finishIfPossible(ActivityRecord.java:2948)
	at com.android.server.wm.ActivityRecord.finishIfPossible(ActivityRecord.java:2880)
	at com.android.server.wm.Task.finishTopCrashedActivityLocked(Task.java:6789)
	at com.android.server.wm.RootWindowContainer.lambda$finishTopCrashedActivities$18(RootWindowContainer.java:2297)
	at com.android.server.wm.RootWindowContainer$$ExternalSyntheticLambda28.accept(Unknown Source:10)
	at com.android.server.wm.Task.forAllTasks(Task.java:3865)
	at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:1720)
	at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:1720)
	at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:1720)
	at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:1720)
	at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:1720)
	at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:1720)
	at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:1720)
	at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:1713)
	at com.android.server.wm.RootWindowContainer.finishTopCrashedActivities(RootWindowContainer.java:2296)
	at com.android.server.wm.ActivityTaskManagerService$LocalService.finishTopCrashedActivities(ActivityTaskManagerService.java:6235)
	at com.android.server.am.AppErrors.handleAppCrashLSPB(AppErrors.java:913)
	at com.android.server.am.AppErrors.makeAppCrashingLocked(AppErrors.java:751)
	at com.android.server.am.AppErrors.crashApplicationInner(AppErrors.java:626)
	at com.android.server.am.AppErrors.crashApplication(AppErrors.java:556)
	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:7921)
	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:88)

[11-04 13:10:51.635 1669:22456 I/ActivityManager]
Process com.coolapk.market (pid 3568) has died: fg  TOP 

[11-04 13:10:51.685 1669:22524 W/InputManager-JNI]
Input channel object 'f8ce0e1 Splash Screen com.coolapk.market (client)' was disposed without first being removed with the input manager!

**Comment by liyiecho** [comment]
不启用插件的情况下，我手机中这版本在安卓12里，也一样闪退，只能更新酷安版本了
